### ISSUE TITLE
Error on integrating

### ISSUE THREAD

**Issue by mesin** [django-tastypie/django-tastypie#1181]
Django version:
(1, 6, 5, 'final', 0)

TastyPie version:
__version__ = (0, 11, 1)

 $ ./manage.py backfill_api_keys
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/Library/Python/2.7/site-packages/tastypie/management/commands/backfill_api_keys.py", line 25, in handle_noargs
    except ApiKey.DoesNotExist:
AttributeError: type object 'ApiKey' has no attribute 'DoesNotExist'

**Comment by SeanHayes** [comment]
That's really odd, Django provides all models with a `*.DoesNotExist` exception.

I'm guessing this may have only been an issue on older versions.
