### ISSUE TITLE
python-mimeparse 1.5 broke the tests

### ISSUE THREAD

**Issue by mattbriancon** [django-tastypie/django-tastypie#1429]
Tests are broken across the board due to a change in python-mimeparse that was just released.

https://github.com/dbtsai/python-mimeparse/commit/f59ab82ee0348f51ddb99a5d104902ea50eb02cc

Need to pin to <1.5 or handle the new exception that's raised.  @SeanHayes thoughts? Happy to work on either approach.

```
(tastypie) matt@jack-kerouac % tox -e py27-dj19
py27-dj19 develop-inst-nodeps: /Users/matt/Projects/vendor/django-tastypie
py27-dj19 installed: biplist==1.0.1,coverage==4.0.3,defusedxml==0.4.1,Django==1.9.2,django-oauth-plus==2.2.8,-e git+git@github.com:django-tastypie/django-tastypie.git@f6ed7d531bb34457ba96d9a66892a9544e86fe4b#egg=django_tastypie,httplib2==0.9.2,lxml==3.5.0,mock==1.0.1,oauth2==1.9.0.post1,pysqlite==2.7.0,python-dateutil==2.4.2,python-digest==1.7,python-mimeparse==1.5,pytz==2013b0,PyYAML==3.11,six==1.10.0,wheel==0.26.0
py27-dj19 runtests: PYTHONHASHSEED='2066402363'
py27-dj19 runtests: commands[0] | /Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/bin/coverage run --append --source=tastypie,tests /Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/bin/django-admin.py test -p * core.tests --settings=settings_core
Creating test database for alias 'default'...
..............................................................................................................E.............................................................................................................................................................................................................................
======================================================================
ERROR: test_determine_format (core.tests.utils.MimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/matt/Projects/vendor/django-tastypie/tests/core/tests/utils.py", line 110, in test_determine_format
    self.assertRaises(BadRequest, determine_format, request, serializer)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/matt/Projects/vendor/django-tastypie/tests/../tastypie/utils/mime.py", line 38, in determine_format
    best_format = mimeparse.best_match(serializer.supported_formats_reversed, accept)
  File "/Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/lib/python2.7/site-packages/mimeparse.py", line 160, in best_match
    parsed_header = [parse_media_range(r) for r in split_header]
  File "/Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/lib/python2.7/site-packages/mimeparse.py", line 75, in parse_media_range
    (type, subtype, params) = parse_mime_type(range)
  File "/Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/lib/python2.7/site-packages/mimeparse.py", line 54, in parse_mime_type
    raise MimeTypeParseException("Can't parse type \"{}\"".format(full_type))
MimeTypeParseException: Can't parse type "bogon"

----------------------------------------------------------------------
Ran 332 tests in 2.259s

FAILED (errors=1)
Destroying test database for alias 'default'...
ERROR: InvocationError: '/Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/bin/coverage run --append --source=tastypie,tests /Users/matt/Projects/vendor/django-tastypie/.tox/py27-dj19/bin/django-admin.py test -p * core.tests --settings=settings_core'
________________________________________________________________________________________________________________________________________________________________________________________________________________ summary ________________________________________________________________________________________________________________________________________________________________________________________________________________
ERROR:   py27-dj19: commands failed
```

**Comment by mattbriancon** [comment]
Discussing here: https://github.com/dbtsai/python-mimeparse/pull/8

**Comment by mattbriancon** [comment]
python-mimeparse pushed a fix. Will run tests against it today to make sure everything's good to go. Still worth considering pinning to a version.

**Comment by SeanHayes** [comment]
Thanks for reporting, I've updated setup.py to disallow python-mimeparse==1.5.
