### ISSUE TITLE
Getting Started with Tastypie: no such table: myapp_entry

### ISSUE THREAD

**Issue by mscheper** [django-tastypie/django-tastypie#1501]
I'm trying to follow the tutoral [Getting Started with Tastypie](http://django-tastypie.readthedocs.io/en/latest/tutorial.html), but when I try to load `/api/entry/?format=json`, I get this HTTP 500 error:

    {"error_message": "no such table: myapp_entry", "traceback": "Traceback (most recent call last):
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
        return Database.Cursor.execute(self, query, params)
    sqlite3.OperationalError: no such table: myapp_entry
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/resources.py", line 219, in wrapper
        response = callback(request, *args, **kwargs)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/resources.py", line 450, in dispatch_list
        return self.dispatch('list', request, **kwargs)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/resources.py", line 482, in dispatch
        response = method(request, **kwargs)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/resources.py", line 1335, in get_list
        to_be_serialized = paginator.page()
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/paginator.py", line 194, in page
        count = self.get_count()
      File "~/myproject/virtualenv/lib/python3.4/site-packages/tastypie/paginator.py", line 126, in get_count
        return self.objects.count()
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 369, in count
        return self.query.get_count(using=self.db)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/models/sql/query.py", line 476, in get_count
        number = obj.get_aggregation(using, ['__count'])['__count']
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/models/sql/query.py", line 457, in get_aggregation
        result = compiler.execute_sql(SINGLE)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
        cursor.execute(sql, params)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "~/myproject/virtualenv/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
        return Database.Cursor.execute(self, query, params)
    django.db.utils.OperationalError: no such table: myapp_entry
    "}

More details about my setup, and what I've already tried, are in [this StackOverflow question](http://stackoverflow.com/questions/42495178/getting-started-with-tastypie-no-such-table-myapp-entry).

I'm not sure if I'm misunderstanding something, or if the tutorial needs updating, but hopefully somebody reading this can offer advice. Thanks.

**Comment by SeanHayes** [comment]
That error is unrelated to Tastypie, the DB table doesn't exist. You'll need to run `manage.py syncdb` or `manage.py migrate`, depending on your Django version. I'd recommend going through the Django tutorials first.

**Comment by mscheper** [comment]
@SeanHayes: As I said in the StackOverflow question, I tried `migrate`. I just tried `syncdb` too, even though I'd never heard of it—it seems Django 1.10 hasn't, either.

I've actually worked on Django sites on and off for pretty close to 10 years, so I don't think this is a Django n00b issue. Would you mind having another look?

**Comment by mscheper** [comment]
@SeanHayes: Thanks for your answer over on StackOverflow. As you spotted, I'd forgotten to add the app to `INSTALLED_APPS`.

It may have been a silly mistake, but I suggest a clarification in the [Configuration](http://django-tastypie.readthedocs.io/en/latest/tutorial.html#configuration) section of the TastyPie tutorial. It states 'The only mandatory configuration is adding "tastypie" to your `INSTALLED_APPS`'—this may be true for installing TastyPie, but it's not correct for following the tutorial.

**Comment by SeanHayes** [comment]
I'm not that involved with this project anymore. If you submit a PR with the doc changes I can merge it for you though.
