### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by adrian410** [django-tastypie/django-tastypie#1504]
When i make a normal POST request, everything works but when i put special caracters in the POST request like "Côte d'Azur" i get this error :

`"'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)"
traceback
:
"Traceback (most recent call last):↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 223, in wrapper↵    response = callback(request, *args, **kwargs)↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 463, in dispatch_list↵    return self.dispatch('list', request, **kwargs)↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 495, in dispatch↵    response = method(request, **kwargs)↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 1403, in post_list↵    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 2202, in obj_create↵    return self.save(bundle)↵↵  File "/home/adrian/Workspace/taxivip/local/lib/python2.7/site-packages/tastypie/resources.py", line 2355, in save↵    bundle.obj.save()↵↵  File "/home/adrian/Workspace/taxivip/src/reservation/models.py", line 73, in save↵    </div>""".format(self.date.replace(tzinfo=None), self.client.nom, self.client.prenom, self.client.phone, self.client.email, self.origine.address,self.destination, self.duree, self.distance, self.car)↵↵UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)↵"
Name
`
If anybody can help me please.

I already tried the following solutions :
 - add "# -*- coding: utf-8 -*-" to the start of my files
 - set unicode function to my models
 - updating my tastypie to master branch
 - add " export LC_ALL=fr_FR.UTF-8
export LANG=fr_FR.UTF-8" to my .bashrc

It drives me crazy.

**Comment by adrian410** [comment]
I had python2.7 version, switched to python3 and the error went away.
