### ISSUE TITLE
Error in version 0.14.2

### ISSUE THREAD

**Issue by dongbohu** [django-tastypie/django-tastypie#1581]
I am trying to upgrade tastypie from 0.13.1 to 0.14.2 (Python 2.7.15rc1, Django 1.11.20), but got this error:
```
Unhandled exception in thread started by <function wrapper at 0x7f1b644edde8>
Traceback (most recent call last):
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tribe/tribe/tribe/urls.py", line 13, in <module>
    from genesets.api.resources import UserResource
  File "/home/tribe/tribe/genesets/api/resources.py", line 415, in <module>
    class GenesetResource(ModelResource):
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/tastypie/resources.py", line 1833, in __new__
    new_class = super(ModelDeclarativeMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/tastypie/resources.py", line 181, in __new__
    field_object.contribute_to_class(new_class, field_name)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/tastypie/fields.py", line 744, in contribute_to_class
    related_field = getattr(self._resource._meta.object_class, self.attribute, None)
TypeError: Error when calling the metaclass bases
    getattr(): attribute name must be string
```
Line 415 of `/home/tribe/tribe/genesets/api/resources.py` is here:
https://github.com/greenelab/tribe/blob/5db4d0b6a07d24ec6aefd62877d9cf7ca1c0ac71/genesets/api/resources.py#L415

This error is reproducible in all tastypie versions later than 0.13.1. Any idea on how to fix it is highly appreciated. Thanks.

**Comment by georgedorn** [comment]
This was the changeset that appears to have caused the issue:

https://github.com/django-tastypie/django-tastypie/commit/af2c1d667f97a1a576e336766d7ac6245263b39d

It works if `attribute` is a string, but if it's a callable, it tries to deduce what the `related_name` for the reverse is and can't.  I suspect that trying to reverse the relationship for a callable attribute is meaningless anyway.  There's a proposed fix in #1482 that needs to be updated for the current matrix of (supported Python * supported Django) versions - it only worked for a narrow set of those at the time it was written.

**Comment by dongbohu** [comment]
Thanks @georgedorn. This is exactly what I reported:
https://github.com/django-tastypie/django-tastypie/commit/af2c1d667f97a1a576e336766d7ac6245263b39d#r29038939

**Comment by georgedorn** [comment]
@dongbohu If you are able, can you try the proposed fix in #1583?  I took a stab at running your tests, but that's clearly a bigger task than it sounds.

I suspect something like:
`pip install -e git+https://github.com/django-tastypie/django-tastypie@6cb7da757fd28e0541adefd7a7261df452123750#egg=TastyPie`

**Comment by dongbohu** [comment]
@georgedorn, I tried the fix, and the tests failed with different error:
```
ERROR: testSearchIndexUpdate (genesets.tests.GenesetUnregisteredTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tribe/tribe/genesets/tests.py", line 299, in testSearchIndexUpdate
    data={'query': 'GO-BP'})
  File "/home/tribe/.virtualenvs/tribe/src/tastypie/tastypie/test.py", line 70, in get
    return self.client.get(uri, **kwargs)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/test/client.py", line 448, in request
    response = self.handler(environ)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/test/client.py", line 122, in __call__
    response = self.get_response(request)
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/tribe/.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tribe/tribe/tribe/urls.py", line 13, in <module>
    from genesets.api.resources import UserResource
  File "/home/tribe/tribe/genesets/api/resources.py", line 1176, in <module>
    class GenesetVersionResource(VersionResource):
  File "/home/tribe/.virtualenvs/tribe/src/tastypie/tastypie/resources.py", line 1828, in __new__
    raise ImproperlyConfigured(msg % name)
ImproperlyConfigured: ModelResource (GenesetVersionResource) requires Meta.object_class or Meta.queryset
```
Thanks.

**Comment by georgedorn** [comment]
That's a legitimate issue on your end.  A `ModelResource` now requires that either `object_class` or `queryset` be defined.  This check was added a while back to prevent much more confusing error messages at runtime.

I see your `VersionResource` has `Meta.queryset` but `GenesetVersionResource.Meta` doesn't inherit it.

**Comment by dongbohu** [comment]
@georgedorn: All tests passed after I added `queryset` to `GenesetVersionResource.Meta`! Thank you very much for your help!

**Comment by georgedorn** [comment]
This is now fixed in `master` and will go out with the next release.  There's a Django update due very soon, so I'll probably wait for that.

Thanks for the help debugging, @dongbohu - there've been a lot of reports of this bug but none thorough enough to be sure of the fix.

**Comment by dongbohu** [comment]
Thanks!
