### ISSUE TITLE
'dict' object has no attribute 'pk' - when trying to GroupBy and Count

### ISSUE THREAD

**Issue by thzois** [django-tastypie/django-tastypie#1609]
Hello,

I am trying to do a group-by and count in one of the API calls. However, it is failing constantly with tastypie. The query produces the correct results, I tried the following:
```
def get_object_list(self, request):
        res = super(CovidResource, self).get_object_list(request)
                 .values('location_name', 'latitude', 'longitude')
                 .annotate(total_incidents=Count('possibly_covid'))
        print(res)
        return res
```

Even though the `print(res)` contains the proper results, `return res` is failing, producing the following trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 499, in dispatch
    response = method(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 1364, in get_list
    for obj in to_be_serialized[self._meta.collection_name]
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 1364, in <listcomp>
    for obj in to_be_serialized[self._meta.collection_name]
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 918, in full_dehydrate
    data[field_name] = method(bundle)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 1092, in dehydrate_resource_uri
    return self.get_resource_uri(bundle)
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 836, in get_resource_uri
    return self._build_reverse_url(url_name, kwargs=self.resource_uri_kwargs(bundle_or_obj))
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 815, in resource_uri_kwargs
    kwargs.update(self.detail_uri_kwargs(bundle_or_obj))
  File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 792, in detail_uri_kwargs
    kwargs[self._meta.detail_uri_name] = getattr(bundle_or_obj, self._meta.detail_uri_name)
AttributeError: 'dict' object has no attribute 'pk'
```

This is my model
```
class CovidIncident(models.Model):
    location_name = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()

    # common-covid
    fever = models.BooleanField()
    dry_cough = models.BooleanField()
    fatigue = models.BooleanField()
    shortness_of_breath = models.BooleanField()

    # sometimes-covid-common-flu
    headache = models.BooleanField()
    loss_of_appetite = models.BooleanField()
    body_aches = models.BooleanField()
    
    #sometimes-covid-sometimes-flu
    runny_nose = models.BooleanField()
    sore_throat = models.BooleanField()

    possibly_covid = models.BooleanField(default=False, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
```

And this is my resource:
```
class CovidResource(ModelResource):
    class Meta:
        API_LIMIT_PER_PAGE = 0
        queryset = CovidIncident.objects.values('location_name', 'latitude', 'longitude').annotate(total_incidents=Count('possibly_covid'))
        resource_name = 'covid'
        limit = 0
        max_limit = 0
        include_resource_uri = True
        allowed_methods = ['get', 'post']
        authentication = ApiKeyAuthentication()
        authorization = DjangoAuthorization()
        validation = Validation()
```

Running django 3.0 and django-tastypie 0.14.3

P.S: Before that, I had `include_resource_uri=False` and I got `ValueError: invalid literal for int() with base 10: ''`.

**Comment by thzois** [comment]
My bad, I just found out that the documentation has `Using Tastypie With Non-ORM Data Sources`. I am closing the issue.
