### ISSUE TITLE
build_filters is only called once when building queryset with relations

### ISSUE THREAD

**Issue by zell2002** [django-tastypie/django-tastypie#1610]
Test URL:
api/v1/parent?child__name__contains=foo

This will give the following error:
The 'name' field does not support relations.

From what I can see in the code base, this API request will call build_filters once, and then check_filtering twice. Once for parent, then for child - which makes sense.

In build_filters, the code gets filter_type from:

	django_field_name = self.fields[field_name].attribute	
	django_field = self._meta.object_class._meta.get_field(django_field_name)

	query_terms = django_field.get_lookups().keys()
	if len(filter_bits) and filter_bits[-1] in query_terms:
		filter_type = filter_bits.pop()

The variables above will be:
`self is parent resource`
`field_name is child resource`
and thus it wont find anything like "contains" etc.. as a filter_type in query_terms

query_terms will be a generic tuple of possible filters:
	`['in', 'exact', 'lt', 'gt', 'gte', 'lte', 'isnull']`

this all then gets passed to check_filtering:
	`self.check_filtering(field_name, filter_type, filter_bits)`

check_filtering will now recieve:
field_name is child
filter_type is exact (cos thats default for the function, if null)
filter_bits is incorrectly ['name', 'contains']

check_filtering will successfully do its first bits, then call it's self again but on the child resource:

	# Recursively descend through the remaining lookups in the filter,
	# if any. We should ensure that all along the way, we're allowed
	# to filter on that field by the related resource.
	related_resource = self.fields[field_name].get_related_resource(None)
	return [self.fields[field_name].attribute] + related_resource.check_filtering(filter_bits[0], filter_type, filter_bits[1:])

The problem now is, check_filtering will be passed:
`field_name` is ``'name'`
`filter_type` is exact (because we're passing through filter_type unchanged)
`filter_bits` is incorrectly `['contains']`

We now get an error:
The 'name' field does not support relations.

Which is because check_filtering is doing this:

	# Check to see if it's a relational lookup and if that's allowed.
	if len(filter_bits):
		if not getattr(self.fields[field_name], 'is_related', False):
			raise InvalidFilterError("The '%s' field does not support relations." % field_name)

It can't find "nameis_related" as a relationship in child.fields.

api/v1/parent?child__name__contains=foo

For this to work, shouldn't the concept of "build_filters" (especially when getting the possible types for a field) be called for every __ relationship in the chain?

I apologise if I've completely miss understood how I should be using this.

**Comment by fatcop** [comment]
I seem to be running into same issue.

**Comment by fatcop** [comment]
Here is a diff to add a testcase replicating the issue.

I only ran the tests for python 3.8 with django 3.0.

But this issue is happening for us on python 3.7 with django 3.1 using tastypie 0.14.3.

Previously we were on a django 1.11 using tastypie 0.14.1.

[tastypie.zip](https://github.com/django-tastypie/django-tastypie/files/5032213/tastypie.zip)

In summary:
```python
class AnotherNoteResource(ModelResource):
    media_bits = fields.ToManyField('tests.core.tests.resources.MediaBitResource', 'media_bits',
        related_name='note', null=True)

    class Meta:
        resource_name = 'notes'
        filtering = {
            'media_bits': ALL_WITH_RELATIONS,
        }
        queryset = Note.objects.filter()


class MediaBitResource(ModelResource):
    note = fields.ToOneField(NoteResource, 'note')

    class Meta:
        queryset = MediaBit.objects.all()
        resource_name = 'mediabit'
        filtering = {
            'title': ALL,
        }
        authorization = Authorization()


class ModelResourceTestCase(TestCase):
     # ....
    def test_build_filters(self):
         # ....
        resource_5 = AnotherNoteResource()
        self.assertEqual(resource_5.build_filters(filters={'media_bits__title__startswith': 'Daniel'}), {'media_bits__title__startswith': 'Daniel'})
```

It fails with:
```
ERROR: test_build_filters (core.tests.resources.ModelResourceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dean/repos/django-tastypie/tests/core/tests/resources.py", line 2153, in test_build_filters
    self.assertEqual(resource_5.build_filters(filters={'media_bits__title__startswith': 'Daniel'}), {'media_bits__title__startswith': 'Daniel'})
  File "/home/dean/repos/django-tastypie/tests/../tastypie/resources.py", line 2101, in build_filters
    lookup_bits = self.check_filtering(field_name, filter_type, filter_bits)
  File "/home/dean/repos/django-tastypie/tests/../tastypie/resources.py", line 2030, in check_filtering
    return [self.fields[field_name].attribute] + related_resource.check_filtering(filter_bits[0], filter_type, filter_bits[1:])
  File "/home/dean/repos/django-tastypie/tests/../tastypie/resources.py", line 2021, in check_filtering
    raise InvalidFilterError("The '%s' field does not support relations." % field_name)
tastypie.exceptions.InvalidFilterError: The 'title' field does not support relations.
```
The initial point of failure seems to be here:

tastypie.resources.py:2096

```python
            query_terms = django_field.get_lookups().keys()
            if len(filter_bits) and filter_bits[-1] in query_terms:
                filter_type = filter_bits.pop()

```
There are similar unittests that are passing, but the difference seems to the relationship model using models.ManytoManyField vs models.ForeignKey.

eg.
```
Subject --m2m-> notes
    vs
MediaBit ->one2many -> note
```
The `query_terms` in that above check returns different things.
ie. you don't get the lookups like `startswith` for ForeignKey type.

So it doesn't pop the final `startswith` from filter_bits and assign it to filter_type when first field is a ForeignKey.

I'm trying to come up with a fix, but think it might be a little more involved.

Any suggested solution would be welcome, as this issue is blocking us from our upgrade path.

**Comment by fatcop** [comment]
I have forked and created a change request for a stab at a fix.

https://github.com/django-tastypie/django-tastypie/pull/1615

After the initial logic change, there was a failing test which I have fixed.

It seems like it actually should fail (doing a __startswith directly on a user relation), so I have changed the test to add __username__startswith.

Then it failed because user/author filter in resource was ALL not ALL_WITH_RELATIONS, so I changed that resource filter to latter.

Hopefully I haven't messed with the space-time continuum updating those.

The travis tests seem to be passing so far.

I am going to test this against our production code now.
