### ISSUE TITLE
tox tests : error with setup.py

### ISSUE THREAD

**Issue by revolunet** [django-tastypie/django-tastypie#278]
Hi

I try to fix some issues and i get error while running tox tests. Im not a tox expert at all :)

When installing virtualenvs and running tastypie setup.py, something weirds going on : 

```
/Users/juju/Documents/projects/django-tastypie/.tox/py25-1.2.X/log$ ../bin/pip install --download-cache=/Users/juju/Documents/projects/django-tastypie/.tox/_download ../../dist/django-tastypie-1.0.0-beta.zip >2.log
Unpacking /Users/juju/Documents/projects/django-tastypie/.tox/dist/django-tastypie-1.0.0-beta.zip
  Running setup.py egg_info for package from file:///Users/juju/Documents/projects/django-tastypie/.tox/dist/django-tastypie-1.0.0-beta.zip
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/folders/n2/31w34qld7gs4dc1m2f_hkyzw0000gn/T/pip-4fQhAJ-build/setup.py", line 17, in <module>
        long_description=open('README.rst', 'r').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/folders/n2/31w34qld7gs4dc1m2f_hkyzw0000gn/T/pip-4fQhAJ-build/setup.py", line 17, in <module>

    long_description=open('README.rst', 'r').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /Users/juju/.pip/pip.log
~                                                        
```

looks like `setup.py` cant find 'README.rst' in the package directory. Which is correct as in the `build`directory i only have : 
- PKG-INFO
- django_tastypie.egg-info
- pip-egg-info
- setup.cfg
- setup.py
- tastypie

Is the `long_description=open('README.rst', 'r').read(),` line in setup.py correct ? mandatory ?

Id love to run the tests,  what can i do ?

Thanks.

Julien

**Comment by nueverest** [comment]
Something that worked for me was creating a MANIFEST.in file as suggested here: http://stackoverflow.com/a/24723873/1783439
