### ISSUE TITLE
Test client's patch method doesn't work properly

### ISSUE THREAD

**Issue by ondrowan** [django-tastypie/django-tastypie#597]
If I send patch data in functional test, I always get following exception:

```
Traceback (most recent call last):
  File "/Users/ondrej/Sites/_work/*******/tests/*******/test_*******_resource.py", line 119, in test_patch_valid_resource
    self.assertHttpAccepted(self.api_client.patch('{0}{1}/'.format(self.uri, *******.id), data=patch_data))
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/test.py", line 179, in patch
    return self.client.request(**r)
  File "/Users/ondrej/.virtualenvs/*******/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/ondrej/.virtualenvs/*******/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/resources.py", line 196, in wrapper
    response = callback(request, *args, **kwargs)
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/resources.py", line 430, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/resources.py", line 450, in dispatch
    response = method(request, **kwargs)
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/resources.py", line 1405, in patch_detail
    deserialized = self.deserialize(request, request.raw_post_data, format=request.META.get('CONTENT_TYPE', 'application/json'))
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/resources.py", line 370, in deserialize
    deserialized = self._meta.serializer.deserialize(data, format=request.META.get('CONTENT_TYPE', 'application/json'))
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/serializers.py", line 194, in deserialize
    deserialized = getattr(self, "from_%s" % desired_format)(content)*******
  File "/Users/ondrej/.virtualenvs/*******/src/tastypie/tastypie/serializers.py", line 344, in from_json
    return simplejson.loads(content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 376, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 1 (char 1)
```

My test case looks approximately like this:

``` python
def test_patch_valid_resource(self):
    contest = ContestFactory.create(created_by=self.user, type=self.type)

    new_name = 'Patched contest #1'

    patch_data = {
        'name': new_name,
    }

    self.assertHttpAccepted(self.api_client.patch('{0}{1}/'.format(self.uri, contest.id), data=patch_data))

    edited_contest = Contest.objects.get()

    self.assertEqual(Contest.objects.count(), 1)
    self.assertEqual(edited_contest.name, new_name)
```

From what I could trace, request object cuts `request.raw_post_data` to `{"name": "Patch` (in this particular test) for some reason. I'm not even sure if it's Tastypie error at all, but patch method is unusable in tests this way.

**Comment by SeanHayes** [comment]
Bug is in currently unsupported version of Django.
