### ISSUE TITLE
Related field "blank" option.

### ISSUE THREAD

**Issue by dbajal** [django-tastypie/django-tastypie#780]
Hi. I've next resources:
```python
class DomainResource(ModelResource):
    class Meta:
        always_return_data = True
        queryset = Domain.objects.all()
        resource_name = 'domain'


class ZoneResource(ModelResource):
    domain = fields.ForeignKey(DomainResource, 'domain', full=True, blank=False)
    class Meta:
        always_return_data = True
        queryset = Zone.objects.all()
        resource_name = 'zone'
```
And when i try to POST "zone" without "domain" i get next error:
```python
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 192, in wrapper
    response = callback(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 397, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 427, in dispatch
    response = method(request, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 1165, in post_list
    updated_bundle = self.obj_create(bundle, request=request, **self.remove_api_resource_names(kwargs))

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 1774, in obj_create
    bundle = self.full_hydrate(bundle)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/resources.py", line 698, in full_hydrate
    value = field_object.hydrate(bundle)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/fields.py", line 637, in hydrate
    value = super(ToOneField, self).hydrate(bundle)

  File "/usr/local/lib/python2.7/site-packages/django_tastypie-0.9.11-py2.7.egg/tastypie/fields.py", line 154, in hydrate
    elif self.attribute and getattr(bundle.obj, self.attribute, None):

  File "/usr/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/fields/related.py", line 343, in __get__
    raise self.field.rel.to.DoesNotExist

DoesNotExist
```
I took a look at 
line 154 of "fields" module:
```python
elif self.attribute and getattr(bundle.obj, self.attribute, None):
```
This makes call of zone_instance.__get__ from django.db.models.fields.related.ReverseSingleRelatedObjectDescriptor and it falls into the DoesNotExist error.
I think the check at tastypie/fields.py:154 should be written like this:
```python
elif self.attribute and bundle.obj.pk and getattr(bundle.obj, self.attribute, None):
```

**Comment by SeanHayes** [comment]
I think this was fixed in d959440bde59c692a0578671519d26a1b95fbe5f.
