### ISSUE TITLE
ImportError: cannot import name create_api_key

### ISSUE THREAD

**Issue by erikcw** [django-tastypie/django-tastypie#937]
When trying to access an API endpoint, this traceback is intermittently raised.

```
Traceback (most recent call last):

  File "django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/app/retargeting/urls.py", line 11, in <module>
    admin.autodiscover()
  File "django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/admin.py", line 6, in <module>
    from tastypie.models import ApiKey
  File "tastypie/models.py", line 31, in <module>
    from tastypie.compat import AUTH_USER_MODEL
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/compat.py", line 13, in <module>
    User = get_user_model()
  File "django/contrib/auth/__init__.py", line 125, in get_user_model
    user_model = get_model(app_label, model_name)
  File "django/db/models/loading.py", line 230, in get_model
    self._populate()
  File "django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name)
  File "django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/app/api/models.py", line 3, in <module>
    from tastypie.models import create_api_key
ImportError: cannot import name create_api_key 
```

For reference, /app/api/models.py

```
from django.contrib.auth.models import User
from django.db import models
from tastypie.models import create_api_key

models.signals.post_save.connect(create_api_key, sender=User)
```

I'm able to import create_api_key from the python REPL without any problems.

Django 1.5.1
Tastypie 0.9.15
Deployed on Heroku.

**Comment by SeanHayes** [comment]
Like @imsickofmaps suggested, specify tastypie as a migration dependency.
